(function () {
  "use strict";
  const PARTS = [
    ["User","ユーザー","👤"],["PC","PC","💻"],["Internet","インターネット","🌐"],["Router","ルーター","📡"],["Switch","スイッチ","⇄"],["Firewall","ファイアウォール","🛡️"],["Load Balancer","ロードバランサー","⚖️"],["Server","サーバー","▤"],["VM","仮想マシン","▣"],["Web Server","Webサーバー","▥"],["Application Server","APサーバー","⚙️"],["Database","データベース","◉"],["Storage","ストレージ","▱"],["Docker","Docker","🐳"],["Kubernetes","Kubernetes","⎈"],["AWS","AWS","☁️"],["Azure","Azure","◇"],["GCP","GCP","☁"]
  ];
  const TYPE_ALIASES = {internet:"Internet",インターネット:"Internet",user:"User",ユーザー:"User",pc:"PC",alb:"Load Balancer",elb:"Load Balancer",ロードバランサー:"Load Balancer",lb:"Load Balancer",web:"Web Server",webサーバー:"Web Server",server:"Server",サーバー:"Server",ec2:"Server",vm:"VM",db:"Database",database:"Database",データベース:"Database",rds:"Database",router:"Router",ルーター:"Router",switch:"Switch",firewall:"Firewall",cloudfront:"AWS",docker:"Docker",kubernetes:"Kubernetes",k8s:"Kubernetes",aws:"AWS",azure:"Azure",gcp:"GCP",storage:"Storage"};
  const ICONS = Object.fromEntries(PARTS.map(p => [p[0],p[2]]));
  const LABELS = Object.fromEntries(PARTS.map(p => [p[0],p[1]]));
  const fresh = () => ({ nodes: [], edges: [] });
  let state=fresh(), history=[], future=[], selected=null, connectFrom=null, drag=null, zoom=1, saveTimer;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const uid=p=>p+Math.random().toString(36).slice(2,9);
  function inferType(name){const key=name.toLowerCase().replace(/[\s_-]/g,"");return TYPE_ALIASES[key]||Object.entries(TYPE_ALIASES).find(([k])=>key.includes(k))?.[1]||"Server"}
  function portLabel(port, explicit=""){if(explicit)return explicit; return ({443:"HTTPS :443",80:"HTTP :80",22:"SSH :22",3306:"TCP :3306",5432:"TCP :5432",3389:"RDP :3389"})[port]||(port?`TCP :${port}`:"")}
  function normalizeName(raw){return raw.trim().replace(/^(?:the\s+)/i,"").replace(/(?:へ|に)$/g,"").replace(/\s*(\d+)台$/," ").trim()}
  function parseNaturalLanguage(input){
    const model=fresh(), groups=new Map(), addGroup=(raw,count=1)=>{let name=normalizeName(raw); if(!name)return[]; const key=name.toLowerCase(); if(groups.has(key))return groups.get(key); const type=inferType(name), base=(count>1?(name.match(/^(Web|EC2|Server|サーバー)$/i)?name:name.replace(/サーバー$/,"")):name); const ids=[]; for(let i=0;i<count;i++){const label=count>1?`${base}${String(i+1).padStart(2,"0")}`:name;const n={id:uid("n"),name:label,type,note:"",x:0,y:0};model.nodes.push(n);ids.push(n.id)}groups.set(key,ids);groups.set(base.toLowerCase(),ids);return ids};
    let previous=null;
    input.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(line=>{
      line=line.replace(/[：]/g,":").replace(/\s+/g," ");
      if(line==="↓")return;
      const alias=line.match(/^(.+?)は(RDS|EC2|ALB|DB|Webサーバー)$/i); if(alias){const ids=addGroup(alias[1]);ids.forEach(id=>{const n=model.nodes.find(x=>x.id===id);n.name=alias[2];n.type=inferType(alias[2])});groups.set(alias[2].toLowerCase(),ids);return}
      let m=line.match(/^(.+?)\s*(?:→|->|から)\s*(.+?)(?:へ)?(?:\s*:?(\d{2,5}))?$/);
      if(!m&&line!=="↓") m=line.match(/^(.+?)\s+へ\s*(\d{2,5})?$/);
      if(m){let from=m[1],to=m[2],port=m[3]||""; const pm=to.match(/^(.*?)(?:へ)?\s*:?(\d{2,5})$/);if(pm){to=pm[1];port=port||pm[2]} const count=+(to.match(/(\d+)台/)?.[1]||1);to=to.replace(/\d+台/g,"").trim(); const fromIds=addGroup(from), toNames=to.split(/\s*(?:と|、|,)\s*/);const toIds=toNames.flatMap(n=>addGroup(n,count));fromIds.forEach(a=>toIds.forEach(b=>model.edges.push({id:uid("e"),from:a,to:b,label:portLabel(port),direction:"forward"})));previous=toIds;return}
      const standalone=line.match(/^(.+?)(?:\s*(\d+)台)?$/);if(standalone){const ids=addGroup(standalone[1],+(standalone[2]||1));if(previous)previous.forEach(a=>ids.forEach(b=>model.edges.push({id:uid("e"),from:a,to:b,label:"",direction:"forward"})));previous=ids}
    });
    autoLayoutModel(model);return model;
  }
  function autoLayoutModel(model){const incoming=new Map(model.nodes.map(n=>[n.id,0]));model.edges.forEach(e=>incoming.set(e.to,(incoming.get(e.to)||0)+1));let layer=model.nodes.filter(n=>!incoming.get(n.id)).map(n=>n.id);if(!layer.length&&model.nodes.length)layer=[model.nodes[0].id];const levels=[],seen=new Set();while(layer.length){levels.push(layer);layer.forEach(x=>seen.add(x));const next=[];layer.forEach(id=>model.edges.filter(e=>e.from===id&&!seen.has(e.to)).forEach(e=>{if(!next.includes(e.to))next.push(e.to)}));layer=next}const rest=model.nodes.filter(n=>!seen.has(n.id)).map(n=>n.id);if(rest.length)levels.push(rest);levels.forEach((ids,l)=>ids.forEach((id,i)=>{const n=model.nodes.find(x=>x.id===id);n.x=250+i*190-(ids.length-1)*95;n.y=100+l*150}));return model}
  function snapshot(){history.push(JSON.stringify(state));if(history.length>60)history.shift();future=[]}
  function mutate(fn){snapshot();fn();render();scheduleSave()}
  function render(){renderNodes();renderEdges();$("#nodeCount").textContent=state.nodes.length;$("#edgeCount").textContent=state.edges.length;renderInspector()}
  function renderNodes(){const root=$("#nodes");root.textContent="";state.nodes.forEach(n=>{const el=document.createElement("div");el.className="node"+(selected?.kind==="node"&&selected.id===n.id?" selected":"")+(connectFrom===n.id?" connecting":"");el.dataset.id=n.id;el.style.cssText=`left:${n.x}px;top:${n.y}px`;el.innerHTML=`<span class="node-icon">${ICONS[n.type]||"▤"}</span><span><strong></strong><small>${LABELS[n.type]||n.type}</small></span>`;el.querySelector("strong").textContent=n.name;root.append(el)})}
  function renderEdges(){const g=$("#edgeLayer");g.textContent="";state.edges.forEach(e=>{const a=state.nodes.find(n=>n.id===e.from),b=state.nodes.find(n=>n.id===e.to);if(!a||!b)return;const x1=a.x+68,y1=a.y+34,x2=b.x+68,y2=b.y+34,vertical=Math.abs(y2-y1)>Math.abs(x2-x1),sx=vertical?x1:(x2>x1?a.x+136:a.x),sy=vertical?(y2>y1?a.y+68:a.y):y1,tx=vertical?x2:(x2>x1?b.x:b.x+136),ty=vertical?(y2>y1?b.y:b.y+68):y2,d=`M${sx},${sy} C${vertical?sx:(sx+tx)/2},${vertical?(sy+ty)/2:sy} ${vertical?tx:(sx+tx)/2},${vertical?(sy+ty)/2:ty} ${tx},${ty}`;const hit=document.createElementNS("http://www.w3.org/2000/svg","path");hit.setAttribute("d",d);hit.setAttribute("class","edge-hit");hit.dataset.id=e.id;const path=document.createElementNS(hit.namespaceURI,"path");path.setAttribute("d",d);path.setAttribute("class","edge-line"+(selected?.kind==="edge"&&selected.id===e.id?" selected":""));path.dataset.id=e.id;if(e.direction==="both")path.style.markerStart="url(#arrowStart)";if(e.direction==="none")path.style.markerEnd="none";g.append(hit,path);if(e.label){const t=document.createElementNS(hit.namespaceURI,"text");t.setAttribute("x",(sx+tx)/2);t.setAttribute("y",(sy+ty)/2-8);t.setAttribute("text-anchor","middle");t.textContent=e.label;g.append(t)}})}
  function renderInspector(){const node=selected?.kind==="node"&&state.nodes.find(n=>n.id===selected.id),edge=selected?.kind==="edge"&&state.edges.find(e=>e.id===selected.id);$("#emptyInspector").hidden=!!(node||edge);$("#nodeInspector").hidden=!node;$("#edgeInspector").hidden=!edge;if(node){$("#nodeName").value=node.name;$("#nodeType").value=node.type;$("#nodeNote").value=node.note||""}if(edge){$("#edgeLabel").value=edge.label;$("#edgeDirection").value=edge.direction}}
  function addNode(type,x=300,y=180,name=LABELS[type]||type){mutate(()=>state.nodes.push({id:uid("n"),name,type,note:"",x,y}))}
  function removeSelected(){if(!selected)return;mutate(()=>{if(selected.kind==="node"){state.nodes=state.nodes.filter(n=>n.id!==selected.id);state.edges=state.edges.filter(e=>e.from!==selected.id&&e.to!==selected.id)}else state.edges=state.edges.filter(e=>e.id!==selected.id);selected=null})}
  function autoLayout(){mutate(()=>autoLayoutModel(state))}
  function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>localStorage.setItem("infraDiagram",JSON.stringify(state)),250)}
  function textOutput(){const roots=state.nodes.filter(n=>!state.edges.some(e=>e.to===n.id));const seen=new Set(),walk=(id,prefix="")=>{const n=state.nodes.find(x=>x.id===id);if(!n)return[];const lines=[prefix+n.name];if(seen.has(id))return lines;seen.add(id);const out=state.edges.filter(e=>e.from===id);out.forEach((e,i)=>{const branch=i===out.length-1?"└→ ":"├→ ",label=e.label?` [${e.label}] `:" ";lines.push(...walk(e.to,prefix+branch+label))});return lines};return (roots.length?roots:state.nodes.slice(0,1)).flatMap(r=>walk(r.id)).join("\n")}
  function mermaidOutput(){const safe=s=>`n_${s.replace(/\W/g,"_")}`,defs=state.nodes.map(n=>`    ${safe(n.id)}["${n.name.replaceAll('"',"'")}"]`),edges=state.edges.map(e=>`    ${safe(e.from)} ${e.direction==="both"?"<-->":e.direction==="none"?"---":"-->"}${e.label?`|${e.label.replaceAll("|","/")}|`:""} ${safe(e.to)}`);return ["graph TD",...defs,...edges].join("\n")}
  function download(name,content,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
  function initialize(){
    $("#parts").innerHTML=PARTS.map(p=>`<div class="part" draggable="true" data-type="${p[0]}"><span class="part-icon">${p[2]}</span><span class="part-name">${p[1]}</span></div>`).join("");$("#nodeType").innerHTML=PARTS.map(p=>`<option>${p[0]}</option>`).join("");
    try{const saved=JSON.parse(localStorage.getItem("infraDiagram"));if(saved?.nodes&&saved?.edges)state=saved}catch(_){/* ignore invalid local data */}render();
    $("#partSearch").oninput=e=>$$('.part').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(e.target.value.toLowerCase()));
    $("#parts").addEventListener("dragstart",e=>e.dataTransfer.setData("text/type",e.target.closest(".part")?.dataset.type||""));$("#canvas").addEventListener("dragover",e=>e.preventDefault());$("#canvas").addEventListener("drop",e=>{e.preventDefault();const type=e.dataTransfer.getData("text/type"),r=$("#world").getBoundingClientRect();if(type)addNode(type,(e.clientX-r.left)/zoom-68,(e.clientY-r.top)/zoom-34)});
    $("#nodes").addEventListener("pointerdown",e=>{const el=e.target.closest(".node");if(!el)return;e.preventDefault();const n=state.nodes.find(x=>x.id===el.dataset.id);if(connectFrom&&connectFrom!==n.id){mutate(()=>state.edges.push({id:uid("e"),from:connectFrom,to:n.id,label:"",direction:"forward"}));connectFrom=null;return}selected={kind:"node",id:n.id};render();snapshot();drag={id:n.id,x:e.clientX,y:e.clientY,nx:n.x,ny:n.y};el.setPointerCapture(e.pointerId)});window.addEventListener("pointermove",e=>{if(!drag)return;const n=state.nodes.find(x=>x.id===drag.id);n.x=Math.max(0,drag.nx+(e.clientX-drag.x)/zoom);n.y=Math.max(0,drag.ny+(e.clientY-drag.y)/zoom);renderNodes();renderEdges()});window.addEventListener("pointerup",()=>{if(drag){drag=null;scheduleSave()}});
    $("#nodes").addEventListener("dblclick",e=>{const id=e.target.closest(".node")?.dataset.id;if(id){connectFrom=id;renderNodes();toast("接続先のノードをクリック")}});$("#edgeLayer").addEventListener("click",e=>{const id=e.target.dataset.id;if(id){selected={kind:"edge",id};render()}});$("#canvas").addEventListener("click",e=>{if(e.target.id==="canvas"||e.target.id==="world"){selected=null;connectFrom=null;render()}});
    ["nodeName","nodeType","nodeNote"].forEach(id=>$("#"+id).addEventListener("change",e=>mutate(()=>{const n=state.nodes.find(x=>x.id===selected.id);n[id==="nodeName"?"name":id==="nodeType"?"type":"note"]=e.target.value})));["edgeLabel","edgeDirection"].forEach(id=>$("#"+id).addEventListener("change",e=>mutate(()=>state.edges.find(x=>x.id===selected.id)[id==="edgeLabel"?"label":"direction"]=e.target.value)));
    document.addEventListener("click",e=>{const a=e.target.closest("[data-action]")?.dataset.action;if(!a)return;if(a==="new"&&confirm("現在の図を消去しますか？"))mutate(()=>{state=fresh();selected=null});if(a==="prompt")$("#promptDialog").showModal();if(a==="layout")autoLayout();if(a==="undo"&&history.length){future.push(JSON.stringify(state));state=JSON.parse(history.pop());selected=null;render()}if(a==="redo"&&future.length){history.push(JSON.stringify(state));state=JSON.parse(future.pop());selected=null;render()}if(a==="delete")removeSelected();if(a==="duplicate"&&selected){const n=state.nodes.find(x=>x.id===selected.id);addNode(n.type,n.x+30,n.y+30,n.name+" copy")}if(a==="connect"&&selected){connectFrom=selected.id;renderNodes();toast("接続先のノードをクリック")}if(a==="theme"){document.documentElement.classList.toggle("dark");localStorage.setItem("infraTheme",document.documentElement.classList.contains("dark")?"dark":"light")}if(a==="save")download("infrastructure-diagram.json",JSON.stringify(state,null,2),"application/json");if(a==="import")$("#jsonFile").click();if(a==="output")showOutput("text");if(a==="zoomin")setZoom(zoom+.1);if(a==="zoomout")setZoom(zoom-.1);if(a==="fit")setZoom(Math.min(1,$("#canvas").clientWidth/900));if(a==="png")exportPng()});
    $("#generateBtn").addEventListener("click",e=>{e.preventDefault();const parsed=parseNaturalLanguage($("#promptText").value);if(!parsed.nodes.length)return toast("解析できる内容がありません");mutate(()=>state=parsed);$("#promptDialog").close();toast(`${state.nodes.length}個のノードを生成しました`)});
    $$("[data-tab]").forEach(b=>b.onclick=()=>showOutput(b.dataset.tab));$("[data-close]").onclick=()=>$("#outputDialog").close();$("#copyOutput").onclick=async()=>{await navigator.clipboard.writeText($("#outputText").value);toast("コピーしました")};
    $("#jsonFile").onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.nodes)||!Array.isArray(data.edges))throw new Error();mutate(()=>{state=data;selected=null});toast("JSONを読み込みました")}catch(_){toast("有効な構成図JSONではありません")}e.target.value=""};
    document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();document.querySelector(`[data-action="${e.shiftKey?"redo":"undo"}"]`).click()}if((e.key==="Delete"||e.key==="Backspace")&&!/INPUT|TEXTAREA/.test(e.target.tagName))removeSelected()});
    if(localStorage.getItem("infraTheme")==="dark"||(!localStorage.getItem("infraTheme")&&matchMedia("(prefers-color-scheme:dark)").matches))document.documentElement.classList.add("dark");
  }
  function setZoom(v){zoom=Math.max(.4,Math.min(1.6,v));$("#world").style.transform=`scale(${zoom})`;$("#zoomLabel").textContent=Math.round(zoom*100)+"%"}
  function showOutput(tab){$("#outputText").value=tab==="mermaid"?mermaidOutput():textOutput();$$('[data-tab]').forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));if(!$("#outputDialog").open)$("#outputDialog").showModal()}
  function exportPng(){const w=1000,h=700,canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=w;canvas.height=h;ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue("--panel")||"white";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#7e8ba1";ctx.lineWidth=2;state.edges.forEach(e=>{const a=state.nodes.find(n=>n.id===e.from),b=state.nodes.find(n=>n.id===e.to);if(!a||!b)return;ctx.beginPath();ctx.moveTo(a.x+68,a.y+34);ctx.lineTo(b.x+68,b.y+34);ctx.stroke();if(e.label){ctx.fillStyle="#536077";ctx.fillText(e.label,(a.x+b.x)/2+68,(a.y+b.y)/2+25)}});state.nodes.forEach(n=>{ctx.fillStyle="#fff";ctx.strokeStyle="#5965e8";ctx.beginPath();ctx.roundRect(n.x,n.y,136,68,10);ctx.fill();ctx.stroke();ctx.fillStyle="#172033";ctx.font="bold 13px sans-serif";ctx.fillText(n.name,n.x+14,n.y+37)});canvas.toBlob(blob=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="infrastructure-diagram.png";a.click();URL.revokeObjectURL(a.href)},"image/png")}
  if(typeof module!=="undefined")module.exports={parseNaturalLanguage,autoLayoutModel,portLabel};if(typeof document!=="undefined")document.addEventListener("DOMContentLoaded",initialize);
})();
