"use strict";
const assert = require("assert");
const fs = require("fs");
const { DEFAULT_TABLES, executeSQL, parseSQL, parseValue } = require("./app.js");
assert.strictEqual(parseValue("true"), true);
assert.strictEqual(parseValue("12.5"), 12.5);
assert.deepStrictEqual(parseSQL("SELECT * FROM users LIMIT 2").limit, 2);
assert.deepStrictEqual(executeSQL("SELECT id, name FROM users WHERE active = true ORDER BY id DESC LIMIT 2", DEFAULT_TABLES), { columns: ["id", "name"], rows: [[4, "田中 健太"], [2, "鈴木 一郎"]] });
assert.deepStrictEqual(executeSQL("SELECT COUNT(*) AS total FROM orders WHERE status = 'paid'", DEFAULT_TABLES), { columns: ["total"], rows: [[2]] });
const tables = JSON.parse(JSON.stringify(DEFAULT_TABLES));
assert.deepStrictEqual(executeSQL("CREATE TABLE tasks (id INTEGER, title TEXT); INSERT INTO tasks (id, title) VALUES (1, '確認'), (2, 'O''Brien'); SELECT * FROM tasks ORDER BY id", tables), { columns: ["id", "title"], rows: [[1, "確認"], [2, "O'Brien"]] });
assert.strictEqual(tables.tasks.rows.length, 2);
assert.deepStrictEqual(executeSQL("DELETE FROM tasks WHERE id = 1; SELECT COUNT(*) AS total FROM tasks", tables), { columns: ["total"], rows: [[1]] });
const snapshot = JSON.stringify(tables);
assert.throws(() => executeSQL("INSERT INTO tasks (missing) VALUES (1)", tables), /列名/);
assert.throws(() => executeSQL("DELETE FROM tasks WHERE missing = 1", tables), /見つかり/);
assert.strictEqual(JSON.stringify(tables), snapshot, "エラー時は途中の変更も反映しない");
assert.throws(() => executeSQL("SELECT * FROM missing", DEFAULT_TABLES), /見つかり/);
assert.match(fs.readFileSync(require.resolve("./styles.css"), "utf8"), /\[hidden\]\{display:none!important\}/);
console.log("SQL Playground tests passed");
