'use strict';
const CATEGORIES=['ファイル操作','ディレクトリ','権限','ユーザー','ネットワーク','SSH','プロセス','ディスク','ログ','systemd','パッケージ管理','圧縮・解凍','grep / sed / awk','Cron','Docker','Git','Kubernetes','OpenShift'];
const KEYS={favorites:'linux-command-explorer:favorites',history:'linux-command-explorer:history',theme:'linux-command-explorer:theme'};
const normalize=value=>String(value||'').toLocaleLowerCase('ja').normalize('NFKC');
function filterCommands(commands,query='',category=''){const q=normalize(query);return commands.filter(c=>(!category||c.category===category)&&(!q||normalize(`${c.name} ${c.description} ${c.category}`).includes(q)));}
function parseOption(option){const index=option.indexOf(':');return index<0?[option,'']:[option.slice(0,index),option.slice(index+1).trim()];}
function safeLoad(key,fallback=[]){try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)?value:fallback}catch{return fallback}}
function init(){
 const el=id=>document.getElementById(id), state={commands:[],query:'',category:'',selected:'',favorites:safeLoad(KEYS.favorites),history:safeLoad(KEYS.history)};
 const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
 const showToast=()=>{el('toast').classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el('toast').classList.remove('show'),2200)};
 const copy=async text=>{try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();document.execCommand('copy');area.remove()}showToast()};
 const select=name=>{const command=state.commands.find(c=>c.name===name);if(!command)return;state.selected=name;state.history=[name,...state.history.filter(x=>x!==name)].slice(0,6);save(KEYS.history,state.history);render();if(innerWidth<761)el('detail').scrollIntoView({behavior:'smooth',block:'start'})};
 function renderSide(){
  el('categoryList').innerHTML=CATEGORIES.map(cat=>`<button class="category ${state.category===cat?'active':''}" data-category="${cat}"><span>${cat}</span><em>${state.commands.filter(c=>c.category===cat).length}</em></button>`).join('');
  const mini=(items,empty)=>items.length?items.map(name=>`<button class="mini-item" data-command="${name}"><span>${name}</span><span>›</span></button>`).join(''):`<p class="mini-empty">${empty}</p>`;
  el('favoriteList').innerHTML=mini(state.favorites,'まだ登録されていません');el('historyList').innerHTML=mini(state.history,'履歴はまだありません');
 }
 function renderDetail(command){if(!command){el('detail').innerHTML='<div class="empty">表示するコマンドを選択してください。</div>';return}
  const optionCommand=`${command.name} ${parseOption(command.options[0])[0]}`;
  el('detail').innerHTML=`<header class="detail-top"><div class="detail-title"><div><span class="category-chip">${command.category}</span><h2>${command.name}</h2><p class="description">${command.description}</p></div><button class="favorite-button ${state.favorites.includes(command.name)?'on':''}" data-favorite>${state.favorites.includes(command.name)?'★ お気に入り':'☆ お気に入り'}</button></div><div class="quick-copy"><button class="copy-button primary" data-copy="name">⌘ コマンドをコピー</button><button class="copy-button" data-copy="example">使用例をコピー</button><button class="copy-button" data-copy="option">オプション付きをコピー</button></div></header><div class="detail-body"><section class="detail-section"><h3 class="section-title">よく使うオプション</h3><div class="option-list">${command.options.map(o=>{const [flag,label]=parseOption(o);return `<div class="option"><code>${flag}</code>${label?` — ${label}`:''}</div>`}).join('')}</div></section><section class="detail-section"><h3 class="section-title">使用例</h3>${command.examples.map(ex=>`<div class="code-block"><code>${ex}</code><button data-copy-text="${encodeURIComponent(ex)}" aria-label="使用例をコピー">▢ COPY</button></div>`).join('')}</section><section class="detail-section"><h3 class="section-title">関連コマンド</h3><div class="related">${command.related.map(r=>`<button data-command="${r}">${r}</button>`).join('')}</div></section></div>`;
  el('detail').querySelector('[data-favorite]').onclick=()=>{state.favorites=state.favorites.includes(command.name)?state.favorites.filter(x=>x!==command.name):[command.name,...state.favorites];save(KEYS.favorites,state.favorites);render()};
  el('detail').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(b.dataset.copy==='name'?command.name:b.dataset.copy==='example'?command.examples[0]:optionCommand));
  el('detail').querySelectorAll('[data-copy-text]').forEach(b=>b.onclick=()=>copy(decodeURIComponent(b.dataset.copyText)));
 }
 function render(){const shown=filterCommands(state.commands,state.query,state.category);if(!shown.some(c=>c.name===state.selected))state.selected=shown[0]?.name||'';el('resultTitle').textContent=state.category|| (state.query?`「${state.query}」の検索結果`:'すべてのコマンド');el('resultCount').textContent=`${shown.length} commands`;el('commandList').innerHTML=shown.length?shown.map(c=>`<button class="command-card ${state.selected===c.name?'active':''}" data-command="${c.name}"><span class="cmd-icon">${c.icon}</span><span><strong>${c.name}</strong><small>${c.description}</small></span><span class="star">${state.favorites.includes(c.name)?'★':''}</span></button>`).join(''):'<div class="empty">一致するコマンドがありません。<br>検索条件を変えてみてください。</div>';renderSide();renderDetail(state.commands.find(c=>c.name===state.selected));document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>select(b.dataset.command));document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;render()})}
 el('searchInput').oninput=e=>{state.query=e.target.value;render()};el('clearFilter').onclick=()=>{state.category='';render()};el('clearHistory').onclick=()=>{state.history=[];save(KEYS.history,[]);render()};document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==el('searchInput')){e.preventDefault();el('searchInput').focus()}});
 const initialTheme=localStorage.getItem(KEYS.theme)||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');document.documentElement.dataset.theme=initialTheme;el('themeToggle').textContent=initialTheme==='dark'?'☀':'☾';el('themeToggle').onclick=()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;localStorage.setItem(KEYS.theme,theme);el('themeToggle').textContent=theme==='dark'?'☀':'☾'};
 fetch('commands.json').then(r=>{if(!r.ok)throw Error('データを読み込めませんでした');return r.json()}).then(commands=>{state.commands=commands;state.selected=commands[0]?.name||'';el('commandCount').textContent=`${commands.length} COMMANDS · ${CATEGORIES.length} CATEGORIES`;render()}).catch(error=>{el('commandList').innerHTML=`<div class="empty">${error.message}</div>`});
}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',init);
if(typeof module!=='undefined')module.exports={filterCommands,parseOption,normalize,CATEGORIES};
